<table class="tablecenter" border="2">
    <tr>
        <th>Waarvoor</th>
        <th>Bron</th>
    </tr>
    <tr>
        <td>rekenmachine</td>
        <td>0920informatica_-_website_-_javascript_rekenmachine.pdf</td>
    </tr>
    <tr>
        <td>Spoiler on image</td>
        <td><a href="https://www.reddit.com/r/html5/comments/4m5g0t/image_spoiler/">https://www.reddit.com/r/html5/comments/4m5g0t/image_spoiler/</a></td>
    </tr>
</table>