version: '3'

services:
  4h-website:
    #image: registry.jelyko.com/4h-website:latest
    build: .
    image: 192.168.178.5:5000/4h-website:1.1.1
    restart: unless-stopped
    ports:
      - 80:80
