<div id="article1">
    <div id="links">
        <h2>Welkom!</h2>
        <p>Ik ben Jasper Demmers, Ik ben 15 jaar oud. Ik zit op dit moment in 4 Havo. Ik ben jarig op 25 februarui. 
            Ik speel professioneel clash of clans. Clash of clans blijft altijd beter dan clash royale. Ik doe in mijn vrije
            tijd veel aan informatica. Ik heb bijvoorbeeld ook een Discord bot gemaakt dat gebruikt maakt van bronnen toen
            ik nog geen informatica had. Ik kan niet wachten tot mijn vervolg opleiding in Eindhoven, ICT infrastructuur en web
            & app development!
        </p>
    </div>
    <div id="rechts">
        <img id="figuur1" src="assets/IMG/handgeschreven-element.jpg" width="300px" height="300px">
    </div>
</div>
<div id="article2">
    <div id="links">
        <img id="figuur1" src="assets/IMG/discord-logo.jpg" width="300px" height="300px">
    </div>
    <div id="rechts">
        <h2>Mijn discord bot</h2>
        <p>Het is een behoorlijk project. Er zit veel javascript in en pug (html) met css erbij. Ik werk er graag
            in mijn vrije tijd. Ik heb met dit project de javascript basics geleerd en ook hoe sites zijn opgebouwd.
            de bot is <a target=_blank href="https://github.com/GiroBot/GiroBot">opensource</a>. Je kunt ook de bot gewoon 
            <a target=_blank href="https://girobot.xyz">inviten</a> naar je discord server!
        </p>
    </div>
</div>