<div id="links">
    <h2>Website 1</h2>
    <p>Een van mijn vele opdrachten is <a target=_blank href="website1/index.html">Website 1</a>. Hij staat nog steeds online! Dit is niet mijn eerste
        website die ik heb gemaakt. Ik heb zelf een hele discord bot gemaakt met een <a target=_blank href="https://girobot.xyz">dashboard</a>. De bot
        is <a target=_blank href="https://github.com/GiroBot/GiroBot">open source</a>.
    </p>
</div>
<div id="rechts">
    <img id="figuur1" src="assets/IMG/opdrachten-figuur1.jpg" width="278px" height="242px">
</div>