<div id="lgo">
    <h2>LGO huis ontwerp</h2>
    <p>January 19 2022: We hebben les over Logo gehad. Een taal waarmee je een turtle dingen kan laten tekenen. Ik heb hiermee mijn huis gemaakt.
        De code is <a target=_blank href="lgo-code.html">hier</a> te zien. Het project staat ook op <a target=_blank href="https://github.com/Jelyko/MWLogo-Example">GitHub</a>
    </p>

    <a target=_blank href="lgo-afbeelding.html"><img id="lgo-afbeelding" src="assets/IMG/lgo-afbeelding.jpg"></a>
    <a target=_blank href="lgo-schets.html"><img id="lgo-schets" src="assets/IMG/lgo-schets.jpg"></a>
    <a target=_blank href="lgo-output.html"><img id="lgo-output" src="assets/IMG/lgo-output.png"></a>
</div>
<div id="links">
    <h2>Website 1</h2>
    <p>Een van mijn vele opdrachten is <a target=_blank href="website1/index.html">Website 1</a>. Hij staat nog steeds online! Dit is niet mijn eerste
        website die ik heb gemaakt. Ik heb zelf een hele discord bot gemaakt met een <a target=_blank href="https://girobot.xyz">dashboard</a>. De bot
        is <a target=_blank href="https://github.com/GiroBot/GiroBot">open source</a>.
    </p>
</div>
